from __future__ import annotations

import re
from typing import Any

from brief import CadBrief, build_brief
from intent import TypedIntent, classify_intent
from standard_library import fastener_spec_from_prompt, looks_like_fastener


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_\u4e00-\u9fff]+", "_", value).strip("_")
    return slug or "component"


def _base_part(name: str, index: int) -> dict[str, Any]:
    return {
        "name": _slug(name),
        "family": "structural",
        "taxonomy": "structural",
        "category": "adaptive_component",
        "type_code": "adaptive_component",
        "standard": None,
        "variant": "planned_component",
        "material": "6061-T6 aluminum",
        "holes": [],
        "chamfers": [{"edge": "all", "size_mm": 0.8, "angle_deg": 45}],
        "fillets": [{"edge": "all", "radius_mm": 1.5}],
        "tolerance": {"plus_mm": 0.1, "minus_mm": 0.1, "note": "Concept-level planning tolerance."},
        "position_mm": [index * 95.0, 0, 0],
        "notes": [f"Generated by part planner from component phrase: {name}"],
        "standard_dimensions": {},
    }


def _planned_component(name: str, index: int) -> dict[str, Any]:
    lower = name.lower()
    x = index * 95.0
    if looks_like_fastener(name) or re.fullmatch(r"M\s*(3|4|5|6|8|10|12|16)", name.strip(), re.IGNORECASE):
        part = fastener_spec_from_prompt(name)["parts"][0]
        part["position_mm"] = [x, -45, 0]
        return part

    base = _base_part(name, index)
    if any(token in lower for token in ["flange", "\u6cd5\u5170", "joint", "\u5173\u8282", "housing", "\u5ea7"]):
        return base | {
            "kind": "flange",
            "geometry_kind": "flange",
            "family": "rotary" if any(token in lower for token in ["joint", "\u5173\u8282"]) else "structural",
            "outer_diameter_mm": 90,
            "inner_diameter_mm": 32,
            "thickness_mm": 18,
            "holes": [{"count": 6, "diameter_mm": 6.6, "bolt_circle_diameter_mm": 68, "through": True, "counterbore_diameter_mm": 11, "counterbore_depth_mm": 4}],
        }
    if any(token in lower for token in ["shaft", "\u8f74", "pin", "\u9500"]):
        return base | {
            "kind": "shaft",
            "geometry_kind": "shaft",
            "family": "rotary",
            "outer_diameter_mm": 24,
            "length_mm": 95,
            "material": "40Cr steel, quenched and tempered",
        }
    if any(token in lower for token in ["link", "arm", "bar", "\u81c2\u6746", "\u8fde\u6746", "\u6746"]):
        return base | {
            "kind": "bracket",
            "geometry_kind": "bracket",
            "length_mm": 160,
            "width_mm": 42,
            "height_mm": 32,
            "thickness_mm": 10,
            "holes": [{"count": 4, "diameter_mm": 6.6, "bolt_circle_diameter_mm": 40, "through": True, "counterbore_diameter_mm": 11, "counterbore_depth_mm": 4}],
        }
    if any(token in lower for token in ["plate", "\u677f", "block", "\u5757"]):
        return base | {
            "kind": "plate" if any(token in lower for token in ["plate", "\u677f"]) else "block",
            "geometry_kind": "plate" if any(token in lower for token in ["plate", "\u677f"]) else "block",
            "length_mm": 100,
            "width_mm": 60,
            "height_mm": 20,
            "thickness_mm": 12,
            "holes": [{"count": 4, "diameter_mm": 6.6, "bolt_circle_diameter_mm": 65, "through": True, "counterbore_diameter_mm": 11, "counterbore_depth_mm": 5}],
        }
    return base | {
        "kind": "bracket",
        "geometry_kind": "bracket",
        "length_mm": 90,
        "width_mm": 60,
        "height_mm": 18,
        "thickness_mm": 10,
        "holes": [{"count": 4, "diameter_mm": 6.6, "bolt_circle_diameter_mm": 55, "through": True, "counterbore_diameter_mm": 11, "counterbore_depth_mm": 4}],
    }


def _single_part_from_intent(brief: CadBrief, intent: TypedIntent) -> dict[str, Any]:
    text = f"{brief.main_object} {brief.prompt}"
    family = intent.generator_family
    if family == "fastener":
        return fastener_spec_from_prompt(brief.prompt)
    if family == "flange":
        outer = 120.0 if "\u5916\u5f84" in text or "120" in text else 90.0
        bore = 35.0 if "35" in text else 30.0
        count = 8 if "8" in text else 6
        part = {
            "name": "planned_flange",
            "kind": "flange",
            "geometry_kind": "flange",
            "family": "rotary",
            "standard": None,
            "variant": "planned_flange",
            "material": "42CrMo4 steel, quenched and tempered",
            "outer_diameter_mm": outer,
            "inner_diameter_mm": bore,
            "thickness_mm": 16,
            "holes": [{"count": count, "diameter_mm": 8.5, "bolt_circle_diameter_mm": outer * 0.8, "through": True, "counterbore_diameter_mm": 14, "counterbore_depth_mm": 5}],
            "chamfers": [{"edge": "both", "size_mm": 1.0, "angle_deg": 45}, {"edge": "holes", "size_mm": 0.5, "angle_deg": 45}],
            "fillets": [{"edge": "both", "radius_mm": 1.5}],
            "tolerance": {"plus_mm": 0.05, "minus_mm": 0.05, "note": "Planned flange tolerance."},
            "position_mm": [0, 0, 0],
            "notes": ["Generated by deterministic flange planner."],
            "standard_dimensions": {},
        }
    elif family in {"plate_block", "bracket"}:
        part = _planned_component(brief.main_object, 0)
        part["name"] = "planned_mounting_block" if family == "plate_block" else part["name"]
    elif family == "shaft":
        part = _planned_component(brief.main_object, 0)
    else:
        part = _planned_component(brief.main_object, 0)

    return _assembly_from_parts(brief, intent, [part], "planner:single_part")


def _assembly_from_parts(brief: CadBrief, intent: TypedIntent, parts: list[dict[str, Any]], source: str) -> dict[str, Any]:
    return {
        "project_name": _slug(intent.main_object)[:64] or "planned_cad_model",
        "unit": "mm",
        "description": brief.prompt,
        "decomposition": {
            "main_object": intent.main_object,
            "scope": intent.scope,
            "requested_output": intent.requested_output,
            "functional_components": intent.components,
            "standard_part_mentions": intent.standard_part_mentions,
            "assumptions": intent.assumptions + [f"Planning source: {source}"],
        },
        "parts": parts,
        "manufacturing_notes": [
            "Generated by deterministic planner; verify dimensions and load cases before manufacturing.",
            "Use generated validation summary to decide whether repair iteration is required.",
        ],
    }


def plan_from_brief(brief: CadBrief, intent: TypedIntent) -> dict[str, Any]:
    if intent.scope == "standard_part" or intent.generator_family == "fastener":
        return fastener_spec_from_prompt(brief.prompt)

    if intent.scope in {"multi_part_assembly", "robot_description"}:
        components = intent.components or [intent.main_object, "mounting interface", "functional feature"]
        parts = [_planned_component(component, index) for index, component in enumerate(components)]
        return _assembly_from_parts(brief, intent, parts, "planner:multi_part")

    return _single_part_from_intent(brief, intent)


def plan_from_prompt(prompt: str) -> tuple[dict[str, Any], str]:
    brief = build_brief(prompt)
    intent = classify_intent(brief)
    return plan_from_brief(brief, intent), f"planner:{intent.generator_family}:{intent.scope}"


def plan_from_candidate(prompt: str, candidate: dict[str, Any] | None) -> tuple[dict[str, Any], str]:
    brief = build_brief(prompt)
    intent = classify_intent(brief)
    if candidate and intent.scope not in {"standard_part"}:
        candidate_scope = ((candidate.get("decomposition") or {}).get("scope") or "").lower()
        candidate_parts = candidate.get("parts") or []
        if candidate_parts and candidate_scope not in {"standard_part"}:
            candidate.setdefault("decomposition", {})
            candidate["decomposition"].setdefault("main_object", intent.main_object)
            candidate["decomposition"].setdefault("scope", intent.scope)
            candidate["decomposition"].setdefault("requested_output", intent.requested_output)
            candidate["decomposition"].setdefault("functional_components", intent.components)
            candidate["decomposition"].setdefault("standard_part_mentions", intent.standard_part_mentions)
            candidate["decomposition"].setdefault("assumptions", intent.assumptions)
            return candidate, "planner:accepted_candidate"
    return plan_from_brief(brief, intent), f"planner:{intent.generator_family}:{intent.scope}"
