from __future__ import annotations

import re

from standard_library import fastener_spec_from_prompt, is_larger_assembly_request, is_primary_fastener_request, looks_like_fastener


def _split_components(prompt: str) -> list[str]:
    text = prompt.strip()
    markers = ["\u7531", "\u5305\u62ec", "\u5305\u542b", "with", "including", "composed of", "consisting of"]
    lower = text.lower()
    start = -1
    marker_len = 0
    for marker in markers:
        idx = lower.find(marker.lower())
        if idx >= 0 and (start < 0 or idx < start):
            start = idx
            marker_len = len(marker)
    if start >= 0:
        text = text[start + marker_len :]
    text = re.split(r"\u7ec4\u6210|\u5bfc\u51fa|export|output", text, maxsplit=1, flags=re.IGNORECASE)[0]
    chunks = re.split(r"[,，、;；/]| and | with |\+", text)
    components = []
    for chunk in chunks:
        name = chunk.strip(" .:-")
        name = re.sub(r"^(several|some|multiple|\u82e5\u5e72|\u4e00\u4e2a|\u4e00\u4ef6)\s*", "", name, flags=re.IGNORECASE)
        if 1 < len(name) <= 40 and name not in components:
            components.append(name)
    return components[:8]


def _component_part(component: str, index: int) -> dict:
    lower = component.lower()
    x = index * 95.0
    base = {
        "name": re.sub(r"[^a-zA-Z0-9_\u4e00-\u9fff]+", "_", component).strip("_") or f"component_{index + 1}",
        "family": "structural",
        "standard": None,
        "variant": "adaptive_component",
        "material": "6061-T6 aluminum",
        "holes": [],
        "chamfers": [{"edge": "all", "size_mm": 0.8, "angle_deg": 45}],
        "fillets": [{"edge": "all", "radius_mm": 1.5}],
        "tolerance": {"plus_mm": 0.1, "minus_mm": 0.1, "note": "Concept-level adaptive fallback tolerance."},
        "position_mm": [x, 0, 0],
        "notes": [f"Adaptive fallback component inferred from phrase: {component}"],
        "standard_dimensions": {},
    }
    if looks_like_fastener(component) or re.fullmatch(r"M\s*(3|4|5|6|8|10|12|16)", component.strip(), re.IGNORECASE):
        return fastener_spec_from_prompt(component)["parts"][0] | {"position_mm": [x, -45, 0]}
    if any(token in lower for token in ["flange", "\u6cd5\u5170", "joint", "\u5173\u8282", "housing", "\u5ea7"]):
        return base | {
            "kind": "flange",
            "outer_diameter_mm": 90,
            "inner_diameter_mm": 32,
            "thickness_mm": 18,
            "holes": [{"count": 6, "diameter_mm": 6.6, "bolt_circle_diameter_mm": 68, "through": True, "counterbore_diameter_mm": 11, "counterbore_depth_mm": 4}],
        }
    if any(token in lower for token in ["shaft", "\u8f74", "pin", "\u9500"]):
        return base | {
            "kind": "shaft",
            "family": "rotary",
            "outer_diameter_mm": 24,
            "length_mm": 95,
            "material": "40Cr steel, quenched and tempered",
        }
    if any(token in lower for token in ["link", "arm", "bar", "\u81c2\u6746", "\u8fde\u6746", "\u6746"]):
        return base | {
            "kind": "bracket",
            "length_mm": 160,
            "width_mm": 42,
            "height_mm": 32,
            "thickness_mm": 10,
            "holes": [{"count": 4, "diameter_mm": 6.6, "bolt_circle_diameter_mm": 40, "through": True, "counterbore_diameter_mm": 11, "counterbore_depth_mm": 4}],
        }
    return base | {
        "kind": "bracket",
        "length_mm": 90,
        "width_mm": 60,
        "height_mm": 18,
        "thickness_mm": 10,
        "holes": [{"count": 4, "diameter_mm": 6.6, "bolt_circle_diameter_mm": 55, "through": True, "counterbore_diameter_mm": 11, "counterbore_depth_mm": 4}],
    }


def _adaptive_fallback_spec(prompt: str) -> dict:
    components = _split_components(prompt)
    if not components:
        components = ["primary body", "mounting interface", "functional feature"]
    parts = [_component_part(component, index) for index, component in enumerate(components)]
    scope = "multi_part_assembly" if len(parts) > 1 or is_larger_assembly_request(prompt) else "single_part"
    return {
        "project_name": "adaptive_concept_model",
        "unit": "mm",
        "description": prompt,
        "decomposition": {
            "main_object": prompt[:80],
            "scope": scope,
            "requested_output": ["stl", "json", "preview"],
            "functional_components": components,
            "standard_part_mentions": [item for item in components if looks_like_fastener(item)],
            "assumptions": [
                "Generated by adaptive fallback because LLM output was unavailable or rejected.",
                "Dimensions are concept-level placeholders inferred from component nouns, not production drawings.",
            ],
        },
        "parts": parts,
        "manufacturing_notes": [
            "Adaptive fallback output is for concept visualization only.",
            "Confirm load cases, fits, materials, tolerances, and standard part selection before manufacturing.",
        ],
    }


def fallback_spec(prompt: str) -> dict:
    if is_primary_fastener_request(prompt):
        return fastener_spec_from_prompt(prompt)
    return _adaptive_fallback_spec(prompt)
